export const examples: Array<{ input: string; output: string }> = [
  {
    input: "Kevin Bacon finished watching Footloose on March 1st, 2014.",
    output: JSON.stringify(
      {
        turtle: [
          "@prefix schema: <https://schema.org/> .",
          "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
          "",
          "<PLACEHOLDER_ENTITY_1> a schema:WatchAction;",
          "  schema:agent <PLACEHOLDER_ENTITY_2>;",
          "  schema:object <PLACEHOLDER_ENTITY_3>;",
          "  schema:actionStatus schema:CompletedActionStatus;",
          '  schema:startTime "2014-03-01"^^xsd:date .',
          "",
          '<PLACEHOLDER_ENTITY_2> a schema:Person; schema:name "Kevin Bacon" .',
          '<PLACEHOLDER_ENTITY_3> a schema:Movie; schema:name "Footloose" .',
        ].join("\n"),
        entities: [
          {
            placeholderId: "PLACEHOLDER_ENTITY_1",
            entityType: "schema:WatchAction",
            entityName: "Watching Footloose",
            sourceText: "finished watching Footloose",
          },
          {
            placeholderId: "PLACEHOLDER_ENTITY_2",
            entityType: "schema:Person",
            entityName: "Kevin Bacon",
            sourceText: "Kevin Bacon",
          },
          {
            placeholderId: "PLACEHOLDER_ENTITY_3",
            entityType: "schema:Movie",
            entityName: "Footloose",
            sourceText: "Footloose",
          },
        ],
      },
      null,
      2,
    ),
  },
  {
    input: "Alice read the article 'The Future of AI' yesterday.",
    output: JSON.stringify(
      {
        turtle: [
          "@prefix schema: <https://schema.org/> .",
          "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
          "",
          "<PLACEHOLDER_ENTITY_1> a schema:ReadAction;",
          "  schema:agent <PLACEHOLDER_ENTITY_2>;",
          "  schema:object <PLACEHOLDER_ENTITY_3>;",
          "  schema:actionStatus schema:CompletedActionStatus;",
          '  schema:startTime "2025-09-22"^^xsd:date .',
          "",
          '<PLACEHOLDER_ENTITY_2> a schema:Person; schema:name "Alice" .',
          '<PLACEHOLDER_ENTITY_3> a schema:Article; schema:headline "The Future of AI" .',
        ].join("\n"),
        entities: [
          {
            placeholderId: "PLACEHOLDER_ENTITY_1",
            entityType: "schema:ReadAction",
            entityName: "Reading article",
            sourceText: "read the article",
          },
          {
            placeholderId: "PLACEHOLDER_ENTITY_2",
            entityType: "schema:Person",
            entityName: "Alice",
            sourceText: "Alice",
          },
          {
            placeholderId: "PLACEHOLDER_ENTITY_3",
            entityType: "schema:Article",
            entityName: "The Future of AI",
            sourceText: "'The Future of AI'",
          },
        ],
      },
      null,
      2,
    ),
  },
  {
    input: "Maria ate dinner at Mama Mia's Pizza on May 5, 2024.",
    output: [
      "@prefix schema: <https://schema.org/> .",
      "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
      "",
      "<PLACEHOLDER_ENTITY_4> a schema:EatAction;",
      "  schema:agent <PLACEHOLDER_ENTITY_5>;",
      "  schema:object <PLACEHOLDER_ENTITY_6>;",
      '  schema:startTime "2024-05-05"^^xsd:date;',
      "  schema:actionStatus schema:CompletedActionStatus .",
      "",
      '<PLACEHOLDER_ENTITY_5> a schema:Person; schema:name "Maria" .',
      '<PLACEHOLDER_ENTITY_6> a schema:Restaurant; schema:name "Mama Mia\'s Pizza" .',
    ].join("\n"),
  },
  {
    input: "Tom drank a cappuccino at Central Cafe yesterday morning.",
    output: [
      "@prefix schema: <https://schema.org/> .",
      "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
      "",
      "<PLACEHOLDER_ENTITY_7> a schema:DrinkAction;",
      "  schema:agent <PLACEHOLDER_ENTITY_8>;",
      "  schema:object <PLACEHOLDER_ENTITY_9>;",
      "  schema:location <PLACEHOLDER_ENTITY_10>;",
      '  schema:startTime "2025-09-22T09:00:00-07:00"^^xsd:dateTime;',
      "  schema:actionStatus schema:CompletedActionStatus .",
      "",
      '<PLACEHOLDER_ENTITY_8> a schema:Person; schema:name "Tom" .',
      '<PLACEHOLDER_ENTITY_9> a schema:MenuItem; schema:name "Cappuccino" .',
      '<PLACEHOLDER_ENTITY_10> a schema:CafeOrCoffeeShop; schema:name "Central Cafe" .',
    ].join("\n"),
  },
  {
    input: "Bob paid $20 for his lunch.",
    output: [
      "@prefix schema: <https://schema.org/> .",
      "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
      "",
      "<PLACEHOLDER_ENTITY_11> a schema:PayAction;",
      "  schema:agent <PLACEHOLDER_ENTITY_12>;",
      "  schema:object <PLACEHOLDER_ENTITY_13>;",
      '  schema:price "20.00"^^xsd:decimal;',
      '  schema:priceCurrency "USD";',
      "  schema:actionStatus schema:CompletedActionStatus .",
      "",
      '<PLACEHOLDER_ENTITY_12> a schema:Person; schema:name "Bob" .',
      '<PLACEHOLDER_ENTITY_13> a schema:MenuItem; schema:name "Lunch" .',
    ].join("\n"),
  },
  {
    input: "Lisa checked into the Grand Hotel at 3pm on August 10, 2025.",
    output: [
      "@prefix schema: <https://schema.org/> .",
      "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
      "",
      "<PLACEHOLDER_ENTITY_14> a schema:CheckInAction;",
      "  schema:agent <PLACEHOLDER_ENTITY_15>;",
      "  schema:location <PLACEHOLDER_ENTITY_16>;",
      '  schema:startTime "2025-08-10T15:00:00-07:00"^^xsd:dateTime;',
      "  schema:actionStatus schema:CompletedActionStatus .",
      "",
      '<PLACEHOLDER_ENTITY_15> a schema:Person; schema:name "Lisa" .',
      '<PLACEHOLDER_ENTITY_16> a schema:LodgingBusiness; schema:name "Grand Hotel" .',
    ].join("\n"),
  },
  {
    input: "Support sent John an email on March 2, 2025.",
    output: [
      "@prefix schema: <https://schema.org/> .",
      "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
      "",
      "<PLACEHOLDER_ENTITY_17> a schema:EmailAction;",
      "  schema:agent <PLACEHOLDER_ENTITY_18>;",
      "  schema:recipient <PLACEHOLDER_ENTITY_19>;",
      '  schema:startTime "2025-03-02"^^xsd:date;',
      "  schema:actionStatus schema:CompletedActionStatus .",
      "",
      '<PLACEHOLDER_ENTITY_18> a schema:Organization; schema:name "Support" .',
      '<PLACEHOLDER_ENTITY_19> a schema:Person; schema:name "John" .',
    ].join("\n"),
  },
  {
    input: "Alex left a review for The Matrix on Feb 1, 2024.",
    output: [
      "@prefix schema: <https://schema.org/> .",
      "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
      "",
      "<PLACEHOLDER_ENTITY_20> a schema:ReviewAction;",
      "  schema:agent <PLACEHOLDER_ENTITY_21>;",
      "  schema:object <PLACEHOLDER_ENTITY_22>;",
      '  schema:startTime "2024-02-01"^^xsd:date;',
      "  schema:actionStatus schema:CompletedActionStatus;",
      "  schema:result <PLACEHOLDER_ENTITY_23> .",
      "",
      '<PLACEHOLDER_ENTITY_21> a schema:Person; schema:name "Alex" .',
      '<PLACEHOLDER_ENTITY_22> a schema:Movie; schema:name "The Matrix" .',
      "<PLACEHOLDER_ENTITY_23> a schema:Review .",
    ].join("\n"),
  },
  {
    input: "City Arts Council hosts a free park concert on July 12, 2025.",
    output: [
      "@prefix schema: <https://schema.org/> .",
      "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
      "",
      "<PLACEHOLDER_ENTITY_24> a schema:MusicEvent;",
      '  schema:name "Summer Park Concert";',
      '  schema:startDate "2025-07-12T19:00:00-07:00"^^xsd:dateTime;',
      "  schema:location <PLACEHOLDER_ENTITY_25>;",
      "  schema:organizer <PLACEHOLDER_ENTITY_26> .",
      "",
      '<PLACEHOLDER_ENTITY_25> a schema:Park; schema:name "Riverside Park" .',
      '<PLACEHOLDER_ENTITY_26> a schema:Organization; schema:name "City Arts Council" .',
    ].join("\n"),
  },
  {
    input: "The Warriors played a basketball game on May 1, 2025.",
    output: [
      "@prefix schema: <https://schema.org/> .",
      "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
      "",
      "<PLACEHOLDER_ENTITY_27> a schema:SportsEvent;",
      '  schema:name "Warriors Basketball Game";',
      '  schema:startDate "2025-05-01"^^xsd:date;',
      "  schema:performer <PLACEHOLDER_ENTITY_28> .",
      "",
      '<PLACEHOLDER_ENTITY_28> a schema:SportsTeam; schema:name "Warriors" .',
    ].join("\n"),
  },
  {
    input: "John reserved flight UA123 from SFO to EWR on Oct 20, 2025.",
    output: [
      "@prefix schema: <https://schema.org/> .",
      "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
      "",
      "<PLACEHOLDER_ENTITY_29> a schema:FlightReservation;",
      '  schema:reservationId "FL123456";',
      "  schema:reservationStatus <https://schema.org/ReservationConfirmed>;",
      "  schema:underName <PLACEHOLDER_ENTITY_30>;",
      "  schema:reservationFor <PLACEHOLDER_ENTITY_31> .",
      "",
      '<PLACEHOLDER_ENTITY_30> a schema:Person; schema:name "John Smith" .',
      "<PLACEHOLDER_ENTITY_31> a schema:Flight;",
      '  schema:flightNumber "UA123";',
      "  schema:departureAirport <PLACEHOLDER_ENTITY_32>;",
      "  schema:arrivalAirport <PLACEHOLDER_ENTITY_33>;",
      '  schema:departureTime "2025-10-20T08:00:00-07:00"^^xsd:dateTime;',
      '  schema:arrivalTime "2025-10-20T16:00:00-04:00"^^xsd:dateTime .',
      "",
      '<PLACEHOLDER_ENTITY_32> a schema:Airport; schema:iataCode "SFO" .',
      '<PLACEHOLDER_ENTITY_33> a schema:Airport; schema:iataCode "EWR" .',
    ].join("\n"),
  },
  {
    input: "A European trip covered Paris and Rome in June 2025.",
    output: [
      "@prefix schema: <https://schema.org/> .",
      "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
      "",
      "<PLACEHOLDER_ENTITY_34> a schema:Trip;",
      '  schema:name "European Adventure";',
      '  schema:departureTime "2025-06-01"^^xsd:date;',
      '  schema:arrivalTime "2025-06-15"^^xsd:date;',
      "  schema:itinerary <PLACEHOLDER_ENTITY_35>, <PLACEHOLDER_ENTITY_36> .",
      "",
      '<PLACEHOLDER_ENTITY_35> a schema:Place; schema:name "Paris, France" .',
      '<PLACEHOLDER_ENTITY_36> a schema:Place; schema:name "Rome, Italy" .',
    ].join("\n"),
  },
];
